"""third migration

Revision ID: 14d194534132
Revises: cf077d35c23e
Create Date: 2023-02-02 12:12:02.217146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d194534132'
down_revision = 'cf077d35c23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('considerations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_1', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('team_2', sa.String(length=40), nullable=True))
        batch_op.drop_column('team2')
        batch_op.drop_column('team1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('considerations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team1', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team2', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.drop_column('team_2')
        batch_op.drop_column('team_1')

    # ### end Alembic commands ###
