"""sixth migration

Revision ID: 6341eb84ef22
Revises: 7e0310e4fa55
Create Date: 2023-02-22 16:50:08.383178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6341eb84ef22'
down_revision = '7e0310e4fa55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('botstate')
    op.drop_table('considerations')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botstate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stopped', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='botstate_pkey')
    )
    # ### end Alembic commands ###
