"""fifth migration

Revision ID: 7e0310e4fa55
Revises: cf4db81ceab5
Create Date: 2023-02-02 17:57:30.683334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0310e4fa55'
down_revision = 'cf4db81ceab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('considerations', schema=None) as batch_op:
        batch_op.drop_column('game_date_time')
        batch_op.drop_column('curr_date_time')
        batch_op.add_column(sa.Column('game_date_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('curr_date_time', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True))
        """ batch_op.alter_column('game_date_time',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('curr_date_time',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True) """

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('considerations', schema=None) as batch_op:
        batch_op.alter_column('curr_date_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('game_date_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
