"""second migration

Revision ID: cf077d35c23e
Revises: 16ffaf933aaf
Create Date: 2023-02-02 12:07:59.655924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf077d35c23e'
down_revision = '16ffaf933aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('stopped', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('considerations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1', sa.String(length=40), nullable=True),
    sa.Column('team2', sa.String(length=40), nullable=True),
    sa.Column('sport', sa.String(length=40), nullable=True),
    sa.Column('game_date_time', sa.DateTime(), nullable=True),
    sa.Column('curr_date_time', sa.DateTime(), nullable=True),
    sa.Column('bet_window', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('considerations')
    op.drop_table('botstate')
    # ### end Alembic commands ###
