"""fourth migration

Revision ID: cf4db81ceab5
Revises: 14d194534132
Create Date: 2023-02-02 13:05:37.170200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf4db81ceab5'
down_revision = '14d194534132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('considerations', schema=None) as batch_op:
        batch_op.alter_column('game_date_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('curr_date_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('considerations', schema=None) as batch_op:
        batch_op.alter_column('curr_date_time',
               existing_type=sa.String(length=40),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('game_date_time',
               existing_type=sa.String(length=40),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
